stages:

  train:
    cmd: python src/train.py
    params:
    - data.train
    - hyperparams
    deps:
    - src/train.py
    - ${data.train}
    outs:
    - model/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    params:
    - data.train
    deps:
    - model/model.pkl
    - src/evaluate.py
    - ${data.test}
    metrics:
    - metrics.json:
        cache: false


