stages:
  download_data:
    cmd: wget ${data_url} -O ${path.data_all}
    frozen: False
    params:
      - data_url
      - path.data_all
    deps:
      - ${data_url}
    outs:
      - ${path.data_all}

  split_data:
    cmd: python src/split_data.py
    params:
      - train_test_split
      - column_mapping
      - path.data_all
      - path.data_train
      - path.data_test
      - path.data_proportion
      - plt_style
    deps:
      - src/split_data.py
      - ${path.data_all}
    plots:
      - ${path.data_proportion}:
          cache: False
    outs:
      - ${path.data_train}
      - ${path.data_test}

  feature_selection:
    cmd: python src/feature_selection.py
    params:
      - column_mapping
      - feature_selection
      - path.data_all
      - path.data_train
      - path.data_test
      - path.correlation_matrix
      - path.selected_features
      - plt_style
    deps:
      - ${path.data_all}
      - src/feature_selection.py
      - src/plots/correlation_matrix.py
    plots:
      - ${path.correlation_matrix}:
          cache: False
    outs:
      - ${path.selected_features}:
          cache: False

  train_model:
    cmd: python src/train_model.py
    params:
      - path.data_train
      - column_mapping
      - path.selected_features
      - pipeline
      - path.model_bin
    deps:
      - src/train_model.py
      - ${path.data_train}
      - ${path.selected_features}
    outs:
      - ${path.model_bin}

  test_model:
    cmd: python src/test_model.py
    params:
      - path.data_test
      - path.data_train
      - column_mapping
      - path.model_bin
      - path.data_train_pred
      - path.data_test_pred
      - path.metrics
      - path.confusion_matrix
      - path.roc_curve
      - path.score_distribution
      - path.precision_recall_curve
      - path.calibration_curve
      - path.cumulative_distribution
      - path.metrics_table
      - path.classification_report
      - path.selected_features
      - plt_style
    deps:
      - src/test_model.py
      - src/plots/confusion_matrix.py
      - src/plots/roc_curve.py
      - src/plots/score_distribution.py
      - src/plots/precision_recall_curve.py
      - src/plots/cumulative_distribution.py
      - src/plots/calibration_curve.py
      - src/plots/metrics_table.py
      - ${path.data_test}
      - ${path.model_bin}
      - ${path.selected_features}
    plots:
      - ${path.confusion_matrix}:
          cache: False
      - ${path.roc_curve}:
          cache: False
      - ${path.score_distribution}:
          cache: False
      - ${path.precision_recall_curve}:
          cache: False
      - ${path.cumulative_distribution}:
          cache: False
      - ${path.calibration_curve}:
          cache: False
      - ${path.metrics_table}:
          cache: False
      - ${path.classification_report}:
          cache: False
    outs:
      - ${path.data_test_pred}:
          cache: False
      - ${path.data_train_pred}:
          cache: False
    metrics:
      - ${path.metrics}:
          cache: False

  feature_importances:
    cmd:
      - python src/feature_importances.py
    params:
      - path.data_test
      - path.data_train
      - column_mapping
      - path.model_bin
      - path.feature_importances
      - path.selected_features
      - plt_style
    deps:
      - src/feature_importances.py
      - src/plots/feature_importances.py
      - ${path.data_test}
      - ${path.model_bin}
      - ${path.selected_features}
    plots:
      - ${path.feature_importances}:
          cache: False

  # model_card:
  #   cmd:
  #     - python src/model_card.py
  #   params:
  #     - data_train_pred
  #     - data_test_pred
  #     - feature_importance
  #     - metrics
  #     - column_mapping.target
  #     - column_mapping.pos_label
  #     - model_card
  #   deps:
  #     - src/model_card.py
  #     - src/plots
  #     - ${data_train_pred}
  #     - ${data_test_pred}
  #     - ${feature_importance}
  #   outs:
  #     - ${model_card}:
  #         cache: False
