plots:
- dvclive/plots/metrics:
    x: step
stages:

  optimize:
    cmd: python src/optimize.py
    deps:
    - data
    outs:
    - dvclive

metrics:
- dvclive/metrics.json
artifacts:
  model:
    path: dvclive/model/model.pkl
    type: model
params:
- dvclive/params.yaml
