stages:

  download_data:
    cmd: wget ${data_url} -O ${data_all}
    params: 
      - data_url
      - data_all
    deps:
      - ${data_url}
    outs:
      - ${data_all}

  # report_data:
  #   cmd: python src/report_data.py
  #   params:
  #     - data_all
  #     - column_mapping
  #     - report_data_html
  #   deps:
  #     - src/report_data.py
  #     - ${data_all}
  #   outs:
  #     - ${report_data_html}:
  #         cache: False

  split_data:
    cmd: python src/split_data.py
    # TO DO: add plots related to split (e.g. data_proportion.png)
    params: 
      - train_test_split
      - data_all
      - data_train
      - data_test
    deps:
      - src/split_data.py
      - ${data_all}
    outs:
      - ${data_train}
      - ${data_test}

  train_model:
    cmd: python src/train_model.py
    params: 
      - data_train
      - column_mapping.target
      - pipeline
      - model_dst
    deps:
      - src/train_model.py
      - ${data_train}
    outs:
      - ${model_dst}

  test_model:
    cmd: 
      - python src/predict.py
      - python src/report_cls.py
      # - python src/feature_importance.py
      # TO DO: remove params, deps and outs related to src/feature_importance.py
      # TO DO: add plots related to test (e.g. feature_importance.png, confusion_matrix.png, roc_curve.png, score_distribution.png)
    params: 
      - data_test
      - data_train
      - column_mapping.target
      - model_dst
      - data_train_pred
      - data_test_pred
      - report_cls_html
      - metrics
      - feature_importance
    deps:
      - src/predict.py
      - src/report_cls.py
      - src/feature_importance.py
      - ${data_test}
      - ${model_dst}
    outs:
      - ${data_test_pred}:
          cache: False
      - ${data_train_pred}:
          cache: False
      - ${report_cls_html}:
          cache: False
      - ${feature_importance}:
          cache: False
    metrics:
      - ${metrics}

    
  model_card:
    cmd: 
      - python src/model_card.py
    params:
      - data_train_pred
      - data_test_pred
      - feature_importance
      - metrics
      - column_mapping.target
      - column_mapping.pos_label
      - model_card
    deps:
      - src/model_card.py
      - src/plots
      - ${data_train_pred}
      - ${data_test_pred}
      - ${feature_importance}
    outs:
      - ${model_card}:
          cache: False