vars:
  - url:
      train: https://huggingface.co/datasets/pirocheto/phishing-url/resolve/main/data/train.parquet
      test: https://huggingface.co/datasets/pirocheto/phishing-url/resolve/main/data/test.parquet

stages:
  download_data:
    cmd: 
      - mkdir -p data
      - wget ${url.train} -O ${data.train} -q --show-progress
      - wget ${url.test} -O ${data.test} -q --show-progress
    deps:
      - ${url.train}
      - ${url.test}
    outs:
      - data

  train:
    cmd: python src/train.py
    params:
      - data.train
      - hyperparams
    deps:
      - src/train.py
      - ${data.train}
    outs:
      - model/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    params:
      - data.test
    deps:
      - model/model.pkl
      - src/evaluate.py
      - ${data.test}
    metrics:
      - metrics.json:
          cache: false

  create_onnx:
    cmd: python src/pkl2onnx.py
    deps:
      - model/model.pkl
      - src/pkl2onnx.py
    outs:
      - model/model.onnx

  modelcard:
    cmd: python src/modelcard.py
    deps:
      - resources/modelcard
      - metrics.json
      - src/modelcard.py
    outs:
      - model/README.md