data_url: https://raw.githubusercontent.com/pirocheto/dataset-registry/master/phishing-detection/data/dataset_B_05_2020.csv
column_mapping:
  feature: url
  target: status
  pos_label: phishing
  prediction_label: prediction_label
  prediction_proba: prediction_proba
train_test_split:
  test_size: 0.33
  random_state: 42
  shuffle: true
plt_style: Solarize_Light2
path:
  data:
    dir: data
    all: data/all.csv
    raw:
      dir: data/raw
      train: data/raw/train.csv
      test: data/raw/test.csv
    predicted:
      dir: data/predicted
      train: data/predicted/train.csv
      test: data/predicted/test.csv
  results:
    dir: results
    models:
      dir: results/models
      label_encoder: results/models/label_encoder.pkl
      preprocessor: results/models/preprocessor.pkl
      classifier: results/models/classifier.pkl
    metrics: results/metrics.yaml
    classification_report: results/classification_report.png
    plots:
      dir: results/plots
      data_proportion: results/plots/data_proportion.png
      metrics_table: results/plots/metrics_table.png
      confusion_matrix: results/plots/confusion_matrix.png
      roc_curve: results/plots/roc_curve.png
      score_distribution: results/plots/score_distribution.png
      precision_recall_curve: results/plots/precision_recall_curve.png
      calibration_curve: results/plots/calibration_curve.png
      cumulative_distribution: results/plots/cumulative_distribution.png
  final_models:
    dir: models
    onnx_model: models/model.onnx
    pkl_model: models/model.pkl
calibration:
  estimator:
    _target_: sklearn.svm.LinearSVC
    dual: auto
    C: 10
  cv: 5
  _target_: sklearn.calibration.CalibratedClassifierCV
  method: isotonic
classifier:
  estimator:
    _target_: sklearn.svm.LinearSVC
    dual: auto
    C: 10
  cv: 5
  _target_: sklearn.calibration.CalibratedClassifierCV
  method: isotonic
preprocessing:
  target:
    _target_: sklearn.preprocessing.LabelEncoder
  feature:
    _target_: sklearn.pipeline.make_union
    _args_:
    - _target_: sklearn.feature_extraction.text.TfidfVectorizer
      analyzer: char
      ngram_range:
        _target_: builtins.tuple
        _args_:
        - - 1
          - 5
    - _target_: sklearn.feature_extraction.text.TfidfVectorizer
      ngram_range:
        _target_: builtins.tuple
        _args_:
        - - 1
          - 2
estimator:
  _target_: sklearn.svm.LinearSVC
  dual: auto
  C: 10
