[tool.poetry]
name = "phishing-url-detection"
version = "0.1.0"
description = ""
authors = ["pirocheto"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.3.2"
pandas = {extras = ["parquet"], version = "^2.1.3"}
dvc = {extras = ["s3"], version = "^3.30.1"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
