[tool.poetry]
name = "phishing-url-detection"
version = "0.1.0"
description = ""
authors = ["pirocheto"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
scipy = "^1.7.2"
scikit-learn = "^1.3.2"
joblib = "^1.3.2"
typer = "^0.9.0"
numpy = "^1.26.2"
pandas = "^2.1.3"
skl2onnx = "^1.15.0"
jinja2 = "^3.1.2"
tabulate = "^0.9.0"

[tool.poetry.group.dev.dependencies]
dvc = "^3.27.0"
matplotlib = "^3.8.0"
seaborn = "^0.13.0"
catboost = "^1.2.2"
lightgbm = "^4.1.0"
xgboost = "^2.0.1"
numpy = "^1.26.2"
huggingface-hub = { extras = ["cli"], version = "^0.19.4" }
optuna = "^3.4.0"

[tool.poetry.group.test.dependencies]
onnxruntime = "^1.16.2"
datasets = "^2.15.0"

[tool.poetry.group.jupyter.dependencies]
ipykernel = "^6.26.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
