[tool.poetry]
name = "phishing-detection"
version = "0.1.0"
description = ""
authors = ["prochet <pierre-rochet@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
dvc = "^3.27.0"
matplotlib = "^3.8.0"
seaborn = "^0.13.0"
ipykernel = "^6.26.0"
catboost = "^1.2.2"
lightgbm = "^4.1.0"
xgboost = "^2.0.1"
scikit-learn = "^1.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
