# TODO: Add docs and comments
_target_: sklearn.feature_selection.SelectKBest
score_func:
  _target_: builtins.getattr
  _args_:
    - _target_: importlib.import_module
      name: sklearn.feature_selection
    - mutual_info_classif
k: 10
