# Univariate feature selector with configurable strategy.
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.GenericUnivariateSelect.html
_target_: sklearn.feature_selection.GenericUnivariateSelect

score_func: 
  _target_: builtins.getattr
  _args_:
    - _target_: importlib.import_module
      name: sklearn.feature_selection
    # - chi2
    - f_classif
    # - mutual_info_classif


# Feature selection mode.
# "k_best": Select features according to the k highest scores.
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectKBest.html#sklearn.feature_selection.SelectKBest

# "percentile": Select features according to a percentile of the highest scores.
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectPercentile.html#sklearn.feature_selection.SelectPercentile
mode: k_best

# Parameter of the corresponding mode.
# "k_best": Number of top features to select. The “all” option bypasses selection, for use in a parameter search.
# "percentile": Percent of features to keep.
param: 10