# Feature selector that removes all low-variance features.
# This feature selection algorithm looks only at the features (X), 
# not the desired outputs (y), and can thus be used for unsupervised learning.
# https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.VarianceThreshold.html#sklearn.feature_selection.VarianceThreshold
_target_: sklearn.feature_selection.VarianceThreshold

# Features with a training-set variance lower than this threshold will be removed. 
# The default is to keep all features with non-zero variance, 
# i.e. remove the features that have the same value in all samples.
threshold: 1