defaults:
  - _self_
  - path.yaml
  - pipeline.yaml

# Data source URL
data_url: https://raw.githubusercontent.com/pirocheto/dataset-registry/master/phishing-detection/data/dataset_B_05_2020.csv

# Column mapping for data
column_mapping:
  feature: url
  target: status
  pos_label: phishing
  prediction_label: prediction_label
  prediction_proba: prediction_proba

# Train-test split configuration
train_test_split:
  test_size: 0.33
  random_state: 42
  shuffle: true

# Matplotlib style for plotting
plt_style: Solarize_Light2
