defaults:
  - _self_
  - path.yaml
  - pipeline.yaml

# Data source URL
data_url: https://raw.githubusercontent.com/pirocheto/dataset-registry/master/phishing-detection/data/dataset_B_05_2020.csv

# Dtypes for features
feature_dtypes:
  ip: bool
  https_token: bool
  punycode: bool
  port: bool
  tld_in_path: bool
  tld_in_subdomain: bool
  abnormal_subdomain: bool
  prefix_suffix: bool
  random_domain: bool
  shortening_service: bool
  path_extension: bool
  domain_in_brand: bool
  brand_in_subdomain: bool
  brand_in_path: bool
  suspecious_tld: bool
  login_form: bool
  external_favicon: bool
  submit_email: bool
  sfh: bool
  iframe: bool
  popup_window: bool
  onmouseover: bool
  right_clic: bool
  empty_title: bool
  domain_in_title: bool
  domain_with_copyright: bool
  whois_registered_domain: bool
  dns_record: bool
  google_index: bool

# Column mapping for data
column_mapping:
  id: url
  target: status
  pos_label: phishing
  prediction_label: prediction_label
  prediction_proba: prediction_proba

# Train-test split configuration
train_test_split:
  test_size: 0.33
  random_state: 42
  shuffle: true

# Matplotlib style for plotting
plt_style: Solarize_Light2
