defaults:
  - _self_
  - path.yaml
  - pipeline.yaml

data_url: https://raw.githubusercontent.com/pirocheto/dataset-registry/master/phishing-detection/data/dataset_B_05_2020.csv

column_mapping:
  id: url
  target: status
  pos_label: phishing
  prediction: phishing

train_test_split:
  test_size: 0.33
  random_state: 42
  shuffle: true

plt_style: Solarize_Light2
