# Configuration defaults for the machine learning pipeline
defaults:
  - _self_
  - preprocessing/target: LabelEncoder
  - preprocessing/feature: null
  - feature_selection: SelectKBestMutualInfo # Default feature selection method
  - estimator: RandomForest # Default classifier for the pipeline
  - calibration: Isotonic # Default calibration method

# Calibration configuration
calibration:
  estimator: ${estimator} # Calibration estimator, using the default classifier
  cv: 5

# Pipeline configuration
classifier: ${calibration} # Include calibration step as the first step in the pipeline
