defaults:
  - classifier: LogisticRegression
  - calibration: Isotonic

calibration:
  estimator: ${classifier}

pipeline:
  _target_: sklearn.pipeline.make_pipeline
  _args_:
    - ${calibration}
      