cls__estimator__C: 6.792087199308755
cls__estimator__loss: squared_hinge
cls__estimator__tol: 0.005305476467652345
tfidf__c__lowercase: true
tfidf__c__ngram_range: !!python/tuple
- 1
- 3
tfidf__w__lowercase: true
tfidf__w__ngram_range: !!python/tuple
- 1
- 2
