cls__estimator__C: 9.508101251081476
cls__estimator__loss: hinge
cls__estimator__tol: 0.0001467686819669336
tfidf__c__lowercase: false
tfidf__c__ngram_range: !!python/tuple
- 1
- 3
tfidf__w__lowercase: false
tfidf__w__ngram_range: !!python/tuple
- 1
- 5
