cls__estimator__C: 0.13193924383038425
cls__estimator__loss: squared_hinge
cls__estimator__tol: 9.638477153798597e-05
tfidf__char__lowercase: true
tfidf__char__ngram_range: !!python/tuple
- 1
- 5
tfidf__char__use_idf: false
tfidf__word__lowercase: true
tfidf__word__ngram_range: !!python/tuple
- 1
- 3
tfidf__word__use_idf: false
