name: Run Test
run-name: Run Test
on:
  push:
    branches:
      - train
      - dev
jobs:
  publish_model:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.13"
      - name: Install Poetry
        uses: snok/install-poetry@v1 
        with:
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          poetry install --no-root --no-interaction --only test
      - name: Pull model
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          source .venv/bin/activate
          dvc pull live/model/model.pkl live/model/model.onnx
      - name: Run test
        run: |
          source .venv/bin/activate
          pytest